### ISSUE TITLE
技能的合约地址收集

### ISSUE THREAD

**Issue by xilibi2003** [decert-me/backend-go#17]
帮助decert.me 的数据更加完善, 请帮我们补充

**Comment by xilibi2003** [comment]
| 链       | 合约地址                                   | 描述说明           |
| -------- | ------------------------------------------ | ------------------ |
| Polygon  | 0x37da9ea159f5c95923ccc65ecae857c2584a899a | 登链社区 Poap 合约 |
| ethereum | 0x8cc6517e45db7a0803fef220d9b577326a12033f | Link3 合约         |
| BSC      | 0x2723522702093601e6360cae665518c4f63e9da6 | Link3 合约         |

**Comment by 0xdwong** [comment]
decert QUEST:  0xEb475aBDD91E07Db399D33F801f5973c7E4B3610 (Polygon)
decert BADGE: 0xc8E9cd4921E54c4163870092Ca8d9660e967B53d (Polygon)
POAP: 0x22C1f6050E56d2876009903609a2cC3fEf83B415

**Comment by 0xdwong** [comment]
相关 issue 转移到：https://github.com/decert-me/nft-collect/issues/1
